name: Handle Deployment

on:
  workflow_call:
    secrets:
      AWS_LAMBDA_PERMISSIONS:
        required: true   # OIDC role for GitHub Actions to assume
      DEPLOY_LAMBDA_PERMISSIONS:
        required: true   # Policy ARN to attach to Lambda exec role
      EVENTBRIDGE_SCHEDULER:
        required: true   # Scheduler ARN or ARN pattern
      LAMBDA_EXEC_ROLE_V3:
        required: true   # Lambda execution role ARN
      LAMBDA_FUNCTION_ARN:
        required: true   # Lambda function ARN

jobs:
  call-pylint:
    uses: ./.github/workflows/lint.yml

  call-deploy-invoke:
    uses: ./.github/workflows/deploy_lambda.yml
    secrets:
      AWS_LAMBDA_PERMISSIONS:  ${{ secrets.AWS_LAMBDA_PERMISSIONS }}
      DEPLOY_LAMBDA_PERMISSIONS: ${{ secrets.DEPLOY_LAMBDA_PERMISSIONS }}
      EVENTBRIDGE_SCHEDULER: ${{ secrets.EVENTBRIDGE_SCHEDULER }}
      LAMBDA_EXEC_ROLE_V3: ${{ secrets.LAMBDA_EXEC_ROLE_V3 }}
      LAMBDA_FUNCTION_ARN: ${{ secrets.LAMBDA_FUNCTION_ARN }}
