name: Handle Deployment

on:
  workflow_call:
    secrets:
      DEPLOY_LAMBDA_PERMISSIONS:
        required: true   # declare that this reusable workflow expects this secret
      AWS_LAMBDA_PERMISSIONS:
        required: true


jobs:
  call-pylint:
    uses: ./.github/workflows/lint.yml

  call-deploy-invoke:
    uses: ./.github/workflows/deploy_lambda.yml
    secrets:
      DEPLOY_LAMBDA_PERMISSIONS: ${{ secrets.DEPLOY_LAMBDA_PERMISSIONS }}  # forward secret to deploy workflow
      AWS_LAMBDA_PERMISSIONS:  ${{ secrets.AWS_LAMBDA_PERMISSIONS }}